version: 2

sources:
  - name: test2
    description: "Primary Data Warehouse with our traffic and vehicle data."
    database: test2
    schema: public
    tables:
      - name: traffic
        description: "Traffic table with 11 colunms"
        columns:
          - name: id
            description: The primary key for this table 
          - name: track_id
            description: Unique tracking identifier
          - name: v_type
            description: Vehicle type
          - name: traveled_d
            description: Distance travled by the vehicle
          - name: avg_speed
            description: Vehicle's average speed 
          - name: lat
            description: Vehicle's latitude
          - name: lon
            description: Vehicle's longitude
          - name: speed
            description: Vehicle's speed during recording
          - name: lon_acc
            description: Vehicle's lon
          - name: lat_acc
            description: Vehicle's lat
          - name: d_time
            description: Time of recording
models:
  - name: avg_speed_distance
    description: "Average speed of every vehicle type group"
    columns:
      - name: v_type
        description: "Vehicle type"
      - name: avg
        description: "Average speed"
  - name: group_by_time
    description: "Vehicles grouped by time of recoding"
    columns:
      - name: d_time
        description: "Time of recording"
      - name: count
        description: "Count of time groups"
  - name: group_by_vehicle_type
    description: "Vehicles grouped by vehicle type"
    columns:
      - name: v_type
        description: "Vehicle type"
      - name: count
        description: "Count of vehicle groups"
          