version: 2

sources:
  - name: traffic_data
    description: "traffic data"
    database: traffic_data
    schema: public
    tables:
      - name: traffic
        description: "traffic table"
        columns:
          - name: id 
          - name: track_id
          - name: v_type
          - name: traveled_d
          - name: avg_speed
          - name: lat
          - name: lon
          - name: speed
          - name: lon_acc
          - name: lat_acc
          - name: d_time
          